### ISSUE TITLE
isolated idmap generation doesn't respect /etc/subuid

### ISSUE THREAD

**Issue by stefanor** [lxc/incus#1659]
If `security.idmap.isolated` is enabled, incus incorrectly calculates a suitable idmap range for the container. It doesn't use the allocated ranges in `/etc/subuid`.

This means launching containers is broken if `uidmap` is installed, under the default configuration + `security.idmap.isolated=true`.

Verified with the current daily build (`1:0~debian12~202502151122`)

Instructions to reproduce:

1. Install and initialize incus.
2. Observe the default `/etc/subuid` entry: `root:1000000:1000000000` created by the Debian package.
3. Enable isolated idmaps: `incus profile set default security.idmap.isolated=true`
4. Launch an instance. (Succeeds)
5. Observe that the Idmap used is below 1000000.
6. Install `uidmap`
7. Launch an instance (Fails)

**Comment by stgraber** [comment]
Did you try restarting Incus after installing uidmap and before creating your new isolated container? 

We parse the subuid/subgid files on system where they are functional but only on Incus startup. 

If that still doesn't work, try starting Incus with --verbose so it logs the uid/gid maps that it detected.

**Comment by stefanor** [comment]
> Did you try restarting Incus after installing uidmap and before creating your new isolated container?

That does the trick.

I ran into this in an Incus 6.0.2 install (`bookworm-backports), converting existing instances from `security.idmap.isolated=false` to `true`. `volatile.id.base` values were assigned that weren't bootable.

I simply can't reproduce it on a clean machine, now.

It always had `uidmap` installed. And has been rebooted a few times since installation. So I don't know why the bug triggered there. Unfortunately rebooting or restarting incus is very painful, so I can't play too much.

**Comment by stgraber** [comment]
We definitely had some bad logic around this stuff a few releases ago (maybe 6.0.0?) but I did a bunch of rework on the whole uidmap calculation and tested a whole bunch of cases.

The main catch is indeed that Incus parses things on startup. And that existing instances will stick to their maps unless an action is taken that forces a re-calculation.

That's something we may be able to change eventually. We were initially trying very hard not to have to change uid/gid map for a given container because that was involving a full filesystem remap, which we've seen take several hours on some systems (typically those with a lot of files on slow storage, like a backup system). But these days the vast majority of storage options allow for in-kernel mapping (VFS idmap). For those a remap is completely free and there isn't really much of a reason to try to persist the map.

**Comment by TCB13** [comment]
I'm also experiencing this on Debian 13, Incus 6.0.4 from Debian repositories.

The strange part is that I've two VMs running Incus, one was cloned from the other and only one of them shows this behavior.

**VM1 not working:**

```
root@ctvm1:~# cat /etc/subuid /etc/subgid
root:1000000:1000000000
root:1000000:1000000000

root@ctvm1:~# incus launch debian13 test
Launching test

root@ctvm1:~# incus config show test
(...)
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'

root@ctvm1:~# incus config set test security.idmap.isolated true

root@ctvm1:~# incus restart test
Error: Failed to run: /usr/libexec/incus/incusd forkstart test /var/lib/incus/containers /run/incus/test/lxc.conf: exit status 1
Try `incus info --show-log test` for more info
root@ctvm1:~# incus info --show-log test
Name: test
Description:
Status: STOPPED
Type: container
Architecture: x86_64
Created: 2025/09/02 22:33 UTC
Last Used: 2025/09/02 22:34 UTC

Log:

lxc test 20250902223414.375 ERROR    idmap_utils - ../src/lxc/idmap_utils.c:lxc_map_ids:245 - newuidmap failed to write mapping "newuidmap: uid range [0-65536) -> [262144-327680) not allowed": newuidmap 1996 0 262144 65536
lxc test 20250902223414.375 ERROR    start - ../src/lxc/start.c:lxc_spawn:1800 - Failed to set up id mapping.
lxc test 20250902223414.375 ERROR    lxccontainer - ../src/lxc/lxccontainer.c:wait_on_daemonized_start:837 - Received container state "ABORTING" instead of "RUNNING"
lxc test 20250902223414.375 ERROR    start - ../src/lxc/start.c:__lxc_start:2119 - Failed to spawn container "test"
lxc test 20250902223414.375 WARN     start - ../src/lxc/start.c:lxc_abort:1037 - No such process - Failed to send SIGKILL via pidfd 17 for process 1996
lxc 20250902223414.404 ERROR    af_unix - ../src/lxc/af_unix.c:lxc_abstract_unix_recv_fds_iov:218 - Connection reset by peer - Failed to receive response
lxc 20250902223414.404 ERROR    commands - ../src/lxc/commands.c:lxc_cmd_rsp_recv_fds:128 - Failed to receive file descriptors for command "get_init_pid"
```

Already restarted a bunch of times, same problem.

**VM2 Working Fine:**

```
root@ctvm2~# cat /etc/subuid /etc/subgid
root:1000000:1000000000
root:1000000:1000000000

root@ctvm2:~# incus launch debian13 test
Launching test

root@ctvm2:~# incus config show test
(...)
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
 
root@ctvm2:~# incus config set test security.idmap.isolated true

root@ctvm2:~# incus restart test

root@ctvm2:~# incus config show test
(...)
  volatile.idmap.base: "1262144"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1262144,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1262144,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1262144,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1262144,"Nsid":0,"Maprange":65536}]'
 
root@ctvm2:~# incus stop test
root@ctvm2:~# incus delete test
root@ctvm2:~# exit
```

Makes no sense at all as the second VM was perfectly able to do it.

**Comment by TCB13** [comment]
**Update**: I just found the source of the problem making VM1 unable to remap to proper IDs.

I was trying to import that had idmaps < 1000000000. The container was already on the instance but stopped because it wouldn't boot as well.

After removing it was able to create the new `test` container, set `security.idmap.isolated true` and then restart it. Incus proceeded to remap the container like VM2 and everything worked fine there.

@stgraber looks like Incus will look at the idmaps of all existing containers when deciding what range to pick up next and go up from there even if the range is bellow the host's  `/etc/subuid` `/etc/subgid` values. Is this worth a new issue or is it fixed in a new version? I'm kinda stuck in Debian's version for now.

Meanwhile the only way I found to import containers with idmaps < 1000000000 was to create clean containers from an image and then replace the rootfs with the one from the backup and proceed to manually add the devices to the new container.

Much appreciated.

**Comment by garak95** [comment]
This is still an issue for me as well. Fresh debian 13 install with fresh containers on 6.0.4. I've confirmed that /etc/subuid and /etc/sudgid have root's base at 1_000_000 before incus is even installed or any container created. Then Incus tries to allocate in the X00_000 range (e.g. newuidmap 42518 0 393216 65536) so it fails. I've reinstalled the OS multiple times in order to find a step-by-step reproduce but the problem doesn't always occur. I initially thought that it doesn't occur when `security.idmap.isolated=true` is set before any container exists, but alas it still happened once.

When it happens, the only solution is to stop all containers, create copies of all containers (not incus copy, but as TCB13 said), delete the originals, rename the copies, then the volatile state is reset. If a single original container remains before you restart the containers, the problem will return immediately.

This workaround is easy enough to run on zfs deployments but it's a total pain on large dir deployments.

**Comment by gibmat** [comment]
Going through some old issues; if there is a specific fix for this issue, please be sure to ping me or report a bug in the Debian BTS so I can properly cherry-pick it back into Debian's version of Incus for trixie. 🙂
